# Web page title
title: Tom's cave

baseurl: ''

# Global Set up for the all pages
# :title indicates a name of a file, not the title in the tab
permalink: :title

# Sass Set up
sass:
  sass_dir: _sass
  style: compressed

# Set up collections(categories)
collections:
  authors:
    # Create Page from _authors directory.
    output: true

# Set the default layout according to the type of posts.
defaults:
  - scope:
      path: ''
      type: 'authors'
    values:
      layout: 'author'

  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

  - scope:
      path: ''
    values:
      layout: 'default'
